<?php
/** @var $exception \Exception */
$exception = $this->getParam('exception');
?>
<strong>Erreur : <?php echo $exception->getMessage() ?></strong><br/>
Erreur sur la ligne <strong><?php echo $exception->getLine() ?></strong> dans le fichier
<strong><?php echo $exception->getFile() ?></strong><br/>

<?php if (isset($_SERVER["REMOTE_ADDR"])) : ?>
    Adresse IP de l'internaute : <?php echo $_SERVER["REMOTE_ADDR"] . ' ' . gethostbyaddr($_SERVER["REMOTE_ADDR"]) ?><br/>
<?php endif; ?>
<?php if (isset($_SERVER["HTTP_HOST"])) : ?>
    URL appelée : http://<?php echo $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?><br/><br/>
<?php endif; ?>
Trace complète :<br/>

<?php
$retour = $exception->getTrace();
ksort($retour);
?>
<style>td{padding: 3px 5px;}</style>
<table border="1"><tr><th>Fichier</th><th>Ligne</th><th>Fonction</th></tr>
    <?php
    unset($retour[0]);
    foreach ($retour as $trace) :
    ?>
        <tr>
            <td><?php echo ((isset($trace['file'])) ? $trace['file'] : $exception->getFile()) ?></td>
            <td style="text-align: right;"><?php echo ((isset($trace['line'])) ? $trace['line'] : $exception->getLine()) ?></td>
            <td>
                <?php
                echo ((isset($trace['class'])) ? $trace['class'] : '');
                echo (isset($trace['type'])) ? $trace['type'] : '';
                echo (isset($trace['function'])) ? $trace['function'] : '';

                $arguments = array();
                if (!empty($trace['args'])) {
                    foreach ($trace['args'] as $arg) {
                        if (is_array($arg)) {
                            $arguments[] = 'Array';
                        } elseif (is_object($arg)) {
                            $arguments[] = 'Object';
                        } elseif (is_resource($arg)) {
                            $arguments[] = 'Resource';
                        } else {
                            $arg = '"' . $arg . '"';
                            $coupure = (strlen($arg) > 50) ? '...' : '';
                            $arguments[] = substr($arg, 0, 50) . $coupure;
                        }
                    }
                }
                echo '(' . implode(',', $arguments) . ')';
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
